# Generated by Django 3.2.2 on 2021-07-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app4.careeroption'),
        ),
    ]
