# Generated by Django 3.2.2 on 2021-07-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_level_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.careeroption'),
        ),
    ]
