# Generated by Django 3.2.2 on 2021-07-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_student_profile'),
        ('app4', '0003_alter_level_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='student',
            field=models.ManyToManyField(to='app1.Student'),
        ),
    ]
