# Generated by Django 3.2.2 on 2021-07-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0006_studentlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlevel',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.level'),
        ),
    ]
