# Generated by Django 3.2.2 on 2021-07-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0007_studentlevel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlevel',
            name='stats',
            field=models.CharField(choices=[('NC', 'Not Completed'), ('C', 'Completed')], max_length=100, null=True),
        ),
    ]
