# Generated by Django 3.2.2 on 2021-07-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_student_profile'),
        ('app4', '0009_auto_20210708_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careeroption',
            name='stats',
        ),
        migrations.CreateModel(
            name='CareerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NC', 'Not Completed'), ('C', 'Completed')], max_length=100, null=True)),
                ('careeropt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app4.careeroption')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.student')),
            ],
        ),
    ]
