# Generated by Django 3.2.2 on 2021-07-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0010_auto_20210708_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerstatus',
            name='status',
            field=models.CharField(choices=[('Not Completed', 'Not Completed'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
