# Generated by Django 3.2.2 on 2021-07-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_student_profile'),
        ('app4', '0012_alter_careerstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careeroption',
            name='student',
        ),
        migrations.AddField(
            model_name='careeroption',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.student'),
        ),
    ]
