# Generated by Django 3.2.2 on 2021-07-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_student_profile'),
        ('app4', '0015_auto_20210708_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careeroption',
            name='student',
        ),
        migrations.AddField(
            model_name='careeroption',
            name='student',
            field=models.ManyToManyField(to='app1.Student'),
        ),
    ]
