# Generated by Django 3.2.2 on 2021-07-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0016_auto_20210708_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('task_type', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], max_length=50, null=True)),
            ],
        ),
    ]
