# Generated by Django 3.2.2 on 2021-07-08 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0018_task_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobno', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Rejected', 'Rejected')], max_length=200, null=True)),
            ],
        ),
    ]
