# Generated by Django 3.2.2 on 2021-07-08 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_student_profile'),
        ('app4', '0019_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.student'),
        ),
    ]
