# Generated by Django 3.2.2 on 2021-07-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0020_jobapplication_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='jobno',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
