# Generated by Django 3.2.2 on 2021-09-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0023_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
