# Generated by Django 3.2.2 on 2021-07-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredstudent',
            name='address',
            field=models.ManyToManyField(to='app3.Address'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialised',
            field=models.ManyToManyField(to='app3.Department'),
        ),
    ]
