# Generated by Django 3.2.2 on 2021-07-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_auto_20210715_0902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstituteEvent',
        ),
    ]
