# Generated by Django 3.2.2 on 2021-07-17 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_delete_instituteevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app3.registeredstudent')),
            ],
        ),
    ]
