# Generated by Django 3.2.2 on 2021-07-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_rename_premiumservices_premiumservice'),
        ('app3', '0006_teacher_employed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='employed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.institutes'),
        ),
    ]
