# Generated by Django 3.2.2 on 2021-07-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_rename_premiumservices_premiumservice'),
        ('app3', '0007_alter_teacher_employed'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.institutes'),
        ),
    ]
