# Generated by Django 3.2.2 on 2021-07-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='customer',
            new_name='student',
        ),
    ]
