# Generated by Django 3.2.2 on 2021-07-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Engineering', 'Engineering'), ('Entrepreneurship', 'Entrepreneurship'), ('Writer', 'Writer'), ('Mock Job Course', 'Mock Job Course')], max_length=100, null=True)),
            ],
        ),
    ]
