# Generated by Django 3.2.2 on 2021-07-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210702_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ImageField(blank=True, default='dp.jpeg', null=True, upload_to='accounts/'),
        ),
    ]
