# Generated by Django 3.2.2 on 2021-07-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_student_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.institutes')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.student')),
            ],
        ),
    ]
