# Generated by Django 3.2.2 on 2021-07-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutes',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
