# Generated by Django 3.2.2 on 2021-07-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutes',
            name='qsrank',
            field=models.IntegerField(null=True),
        ),
    ]
