# Generated by Django 3.2.2 on 2021-07-13 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_institutes_qsrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgratio', models.CharField(max_length=100, null=True)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.institutes')),
            ],
        ),
    ]
