# Generated by Django 3.2.2 on 2021-07-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
