# Generated by Django 3.2.2 on 2021-07-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_scholarship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='institute',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='institute',
            field=models.ManyToManyField(to='app1.Institutes'),
        ),
    ]
