# Generated by Django 3.2.2 on 2021-07-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20210713_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='applicable',
            field=models.CharField(choices=[('highschool', 'highschool'), ('undergraduate', 'undergraduate'), ('postgraduate', 'postgraduate')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_type',
            field=models.CharField(choices=[('academics', 'academics'), ('competition', 'competition'), ('sports', 'sports'), ('CCA', 'CCA')], max_length=100, null=True),
        ),
    ]
