# Generated by Django 3.2.2 on 2021-07-13 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20210713_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.student'),
        ),
    ]
