# Generated by Django 3.2.2 on 2021-07-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_premiumserivces'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PremiumSerivces',
            new_name='PremiumServices',
        ),
    ]
