# Generated by Django 3.2.2 on 2021-07-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_rename_premiumserivces_premiumservices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PremiumServices',
            new_name='PremiumService',
        ),
    ]
