# Generated by Django 3.2.2 on 2021-08-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_rename_premiumservices_premiumservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutes',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
