# Generated by Django 3.2.2 on 2021-08-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_institutes_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Internship', 'Intersnhips'), ('Full Time Job', 'Full Time Job')], max_length=100, null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('requirements', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
