# Generated by Django 3.2.2 on 2021-08-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_alter_institutes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
