# Generated by Django 3.2.2 on 2021-08-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_job_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
