# Generated by Django 3.2.2 on 2021-08-18 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_auto_20210818_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='institute',
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.event'),
        ),
    ]
