# Generated by Django 3.2.2 on 2021-08-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_auto_20210818_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='event',
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='event',
            field=models.ManyToManyField(null=True, to='app1.Event'),
        ),
    ]
